hotel-project/app/Http/routes.php
<?php
Route::get('/aboutme', 'PagesController@aboutme');

hotel-project/routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
App::register('Gloudemans\Shoppingcart\ShoppingcartServiceProvider');

Auth::routes();

Route::get('/', 'HomeController@index');

Route::prefix('admin')->group(function () {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.admin-template');
    Route::get('/room/create','RoomController@create');
    Route::get('/room/index','RoomController@index');
    Route::resource('/room','RoomController');
});

Route::get('/contact', function () {
    return view('contact');
});
// Route::post('/contact/submit', 'MessagesController@submit');

Route::resource('category','CategoriesController');
Route::get('/admin', 'AdminController@index')->name('admin.admin-template');
// Route::get('/admin/room/create', 'RoomController@create');


Route::prefix('rooms')->group(function (){
    Route::get('/', 'RoomsController@index');
    Route::get('/room-detail', 'RoomsController@roomDetail');
});
Route::resource('/cart','CartController');
//Route::get('/booking','RoomController@booking');
Route::resource('room','RoomController');
Route::resource('/booking','BookingController');
Route::get('/booking/create/{id}', 'BookingController@create');
Route::get('/customer/create/{id}', 'CustomersController@create');
Route::get('/customer/index', 'CustomersController@index');
Route::resource('/customer','CustomersController');
Route::resource('/search','SearchController');
Route::get('/search','SearchController@create');
Route::get('/room/room/{id}','RoomController@roomCates');

hotel-project/resources/views/layouts/admin-theme.blade.php
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Admin Dashboard</title>
    <meta name="description" content="">
    <link rel="stylesheet" href="/css/admin-css.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body class="home">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
    <div class="container-fluid display-table">
        <div class="row display-table-row">
            <div class="col-md-2 col-sm-1 hidden-xs display-table-cell v-align box" id="navigation">
                <div class="navi">
                    <ul>
                        <li class="active"><a href="#"><i class="fa fa-home" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Home</span></a></li>
                        <li><a href="#" id="room-index" data-target="#index"><i class="fa fa-tasks" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Room</span></a></li>
                        <li><a href="#" id="add" data-target="#add_project"><i class="fa fa-bar-chart" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Add room</span></a></li>
                        <li><a href="#"><i class="fa fa-user" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Booking list</span></a></li>
                        <li><a href="#" id="category" data-target="#add_category"><i class="fa fa-calendar" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Add Category</span></a></li>
                        <li><a href="#"><i class="fa fa-cog" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Setting</span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-10 col-sm-11 display-table-cell v-align">
                <!--<button type="button" class="slide-toggle">Slide Toggle</button> -->
                <header class="header">
                    <div class="row">
                    <div class="col-md-7">
                        <nav class="navbar-default pull-left">
                            <div class="navbar-header" style="display: none;">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="offcanvas" data-target="#side-menu" aria-expanded="false">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                            </div>
                        </nav>
                    </div>
                    <div class="col-md-5">
                        <div class="header-rightside">
                            <ul class="list-inline header-top pull-right">
                                <li><img src="/images/admin.jpg" alt="admin"></li><br>
                                <li><a href="#">Hi {{ Auth::user()->name }}</a></li>
                                @if (Auth::guest())
                                <li><a href="{{ route('login') }}">Login</a></li>
                                <li><a href="{{ route('register') }}">Register</a></li>
                                @else
                                <br>
                                <li class="hidden-xs"><a href="{{ route('logout') }}" onclick="event.preventDefault();
                                        document.getElementById('logout-form').submit();" data-toggle="modal">Log out</a></li>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                                @endif
                            </ul>
                        </div>
                    </div>
                </header>
                <div class="user-dashboard">
                    <h3>Welcome to Admin Dashboard</h3>
                    
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/jquery-ui.js"></script>
    <script type="text/javascript" src="/js/custom.js"></script>
</body>
</html>

hotel-project/resources/views/layouts/admin.blade.php
<!DOCTYPE html> 
<html class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Luxury Hotel</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/css/jquery-ui.css">
    <link rel="stylesheet" href="/css/app.css">
</head>
<body>
    <div class="container">
        @yield('content')
    </div>
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/jquery-ui.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/custom.js"></script>
</body>
</html>

hotel-project/resources/views/layouts/adminShow.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>View rooms</title>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-inverse">
            <div class="navbar-header">
                <a class="navbar-brand" href="{{ URL::to('admin') }}">Back to Admin Dashboard</a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="{{ URL::to('admin/room') }}">View All room</a></li>
                <li><a href="{{ URL::to('admin/room/create') }}">Create a Room</a>
            </ul>
        </nav>

        <h2>Showing {{ $room->name }}</h2>
        <div class="col-md-4">
            <img class="room-image" src="/{{ $room->image }}" alt="">
        </div>
        <div class="jumbotron text-center">
            <h2>{{ $room->name }}</h2>
            <p>
                <strong>Price:</strong> {{ $room->price }}<br>
                <strong>Description:</strong> {{ $room->description }}
            </p>
        </div>
    </div>
</body>
</html>

hotel-project/resources/views/layouts/app-bk.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"onclick="event.preventDefault();
                                        document.getElementById('logout-form').submit();">Logout</a>
                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

hotel-project/resources/views/layouts/app.blade.php
<!DOCTYPE html> 
<html class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Luxury Hotel</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/css/app.css">
</head>
<body>
    <header>
        @include('inc.header')
        @include('inc.banner')
    </header>
        
    <div class="container">
    @if(Request::is('/'))
        @include('inc.showcase')
    @endif
        <div class="row">
            <div class="col-md-8 col-lg-8">
                @include('inc.messages')
                @yield('content')
            </div>
            <div class="col-md-4 col-lg-4">
                @if(Request::is('login'))
                    @include('inc.messages')
                @elseif (Request::is('register'))
                    @include('inc.messages')
                @elseif (Request::is('rooms'))
                    @include('inc.messages')
                @else
                    @include('inc.sidebar')
                @endif
            </div>
        </div>
    </div>
    @include('inc.footer')
    <script type="text/javascript" src="/js/custom.js"></script>
</body>
</html>

hotel-project/resources/views/layouts/form.blade.php
<div class="container">
    <div class="form">
    <?php $categories = DB::table('categories')->get();  ?>
        <form class="form-inline" action="{{ route('search.create') }}" method="get">
            <div class="form-group">
                <select name="roomList" id="seclect" class="form-control">
                    <option>Select room</option>
                    @foreach ($categories as $category)
                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <input type="text" id="datefrom" class="form-control" placeholder="Date available" name="dateAvail">
            </div>
            <div class="form-group">
                <input type="text" id="dateto" class="form-control" placeholder="Date unavailable" name="dateUnAvail">
            </div>
            <div class="form-group">
                <input class="form-control" type="text" name="number_people" placeholder="Number of people">
            </div> 
            <button type="submit" class="btn btn-default">Search</button>
        </form>
    </div>
</div>

hotel-project/resources/views/layouts/master.blade.php
<html>
<head>
    <title>Laravel eshop</title>
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/css/style.css">
</head>
<body>
@section('inc.sidebar')
    <nav class="navbar navbar-default  navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Laravel digital Shop</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    @if(!Auth::user())
                        <li><a href="/auth/login">Login</a></li>
                        <li><a href="/auth/register">Signup</a></li>
                    @else
                        <li><a href="/order">My Order <span class="fa fa-briefcase"></span></a></li>
                        <li><a href="/cart">Cart <span class="fa fa-shopping-cart"></span></a></li>
                        <li><a href="/auth/logout">Logout {{ Auth::user()->name}}</a></li>
                    @endif
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
@show
 
<div class="container">
    @yield('content')
</div>
</body>
</html>

hotel-project/resources/views/layouts/room-detail.blade.php
@extends('layouts.theme')
@section('content')
<div class="col-lg-8">
    <div class="l-align-center"><h3>ROOM DETAIL</h3></div>
    <hr>
    <div class="room-content">
        <div class="room-image">
            <img src="/images/room-1.jpg" alt="">
            <div class="overlay"><h3>2101BA</h3></div>
        </div>
        
        <br>
        <table class="table table-border">
            <tr>
                <td>Room name</td>
                <td>2101BA</td>
            </tr>
            <tr>
                <td>Price</td>
                <td>$160</td>
            </tr>
            <tr>
                <td>Type</td>
                <td>Luxury room</td>
            </tr>
            <tr>
                <td>Status</td>
                <td>Availuable</td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" class="btn btn-danger" value="Book now" id="showForm"></td>
            </tr>
        </table>
    </div>

    <div class="div_form">
        <form action="">
            <div class="well clearfix">
                <fieldset class="well well-form">
                    <legend class="well-legend">Booking Details</legend>
                    <div class="row">
                        <div class="col-xs-4">
                            <label class="control-label" for="booking-date">Booking Date</label>
                            <div class="form-group input-group">
                                <span class="input-group-addon "><i class="fa fa-calendar"></i></span>
                                <input class="form-control" type="text" name="booking-date" id="datefrom" placeholder="Booking Date" />
                            </div>
                        </div>

                        <div class="col-xs-4">
                            <label class="control-label" for="booking-date">Check In</label>
                            <div class="form-group input-group">
                                <span class="input-group-addon "><i class="fa fa-calendar-check-o"></i></span>
                                <input class="form-control" type="text" name="booking-date" id="dateto" placeholder="Check In" />
                            </div>
                        </div>

                        <div class="col-xs-2">
                            <label class="control-label" for="form_days">Days</label>
                            <select class="form-control" id="form_days" name="days">
                                <option selected value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>""
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                                <option value="7">7</option>
                                <option value="8">8</option>
                                <option value="9">9</option>
                                <option value="10">10</option>
                            </select>
                        </div>
                    </div>
            <!-- end Row -->
                    <div class="row">
                        <div class="col-xs-2">
                            <label class="control-label" for="form_days">Adults</label>
                            <select class="form-control" id="form_days" name="days">
                                <option selected value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>""
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                                <option value="7">7</option>
                                <option value="8">8</option>
                                <option value="9">9</option>
                                <option value="10">10</option>
                            </select>
                        </div>

                        <div class="col-xs-2">
                            <label class="control-label" for="form_days">Children</label>
                            <select class="form-control" name="days">
                                <option selected value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>""
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                                <option value="7">7</option>
                                <option value="8">8</option>
                                <option value="9">9</option>
                                <option value="10">10</option>
                            </select>
                        </div>
                    </div>
            <!-- end Row -->
            </fieldset>

            <fieldset class="well well-form">
                <legend class="well-legend">Customer</legend>
                    <div class="row">
                        <div class="col-xs-5">
                            <label class="control-label" for="firstname">Name</label>
                            <input class="form-control" type="text" name="firstname" id="firstname" placeholder="Name" />
                            <label class="control-label" for="phoneNumber">Number</label>
                            <div class="form-group input-group">
                                <span class="input-group-addon primary"><i class="fa fa-phone"></i></span>
                                <input type="text" class="form-control" name="phoneNumber" id="phoneNumber" placeholder="Phone Number">
                            </div>

                            <label class="control-label" for="email">Email Address</label>
                            <div class="form-group input-group">
                                <span class="input-group-addon primary"><i class="fa fa-envelope-o"></i></span>
                                <input type="text" class="form-control" name="email" id="email" placeholder="Email address">
                            </div>
                        </div>

                        <div class="col-xs-7">
                            <label class="control-label">Message</label>
                            <textarea class="input-xlarge form-control" id="message" name="message" rows="10"></textarea>
                        </div>
                    </div>
            <!-- end Row -->
            </fieldset>

            <fieldset class="well well-form">
                <legend class="well-legend">Payment</legend>
                <div class="row">
                    <div class='col-xs-6'>
                        <label class='control-label'>Card Number</label>
                        <div class="form-group input-group">
                        <span class="input-group-addon primary"><i class="fa fa-credit-card-alt"></i></span>
                        <input autocomplete='off' class='form-control card-number' size='20' type='text' data-mask="0000 0000 0000 0000">
                        </div>
                    </div>

                    <div class='col-xs-3'>
                        <label class='control-label'>Expiration</label>
                        <input class='form-control card-expiry-month' placeholder='MM' size='2' type='text'>
                    </div>

                    <div class='col-xs-3'>
                        <label class='control-label'> </label>
                        <input class='form-control card-expiry-year' placeholder='YYYY' size='4' type='text'>
                    </div>
                </div>
            <!-- end Row -->
            </fieldset>

                <div class="row">
                    <div class="col-xs-12">
                        <br/>
                        <button class="btn btn-success "><i class="fa fa-pencil"></i> Edit</button>
                        <button class="btn btn-warning "><i class="fa fa-send"></i> Send email Confirmation</button>
                        <button class="btn btn-info pull-right" type="submit"><i class="fa fa-refresh"></i> Reload calendars</button>
                    </div>
                </div>
            <!-- end Row -->

            </div>
        <!-- end Well -->

        </form>
    </div>
</div>
<div class="col-lg-4">
    <!--@include('inc.sidebar')-->
    <div class="room-description">
        <h3>ROOM DESCRIPTION</h3>
        <hr>
        <p>Nulla at mauris accumsan eros ullamcorper tincidunt at nec ipsum. 
        In iaculis est ut sapien ultrices, vel feugiat nulla lobortis. Donec nec quam accumsan, lobortis.</p>
        <p>Nulla at mauris accumsan eros ullamcorper tincidunt at nec ipsum. 
        In iaculis est ut sapien ultrices, vel feugiat nulla lobortis. Donec nec quam accumsan, lobortis.</p>
        <p>Nulla at mauris accumsan eros ullamcorper tincidunt at nec ipsum. 
        In iaculis est ut sapien ultrices, vel feugiat nulla lobortis. Donec nec quam accumsan, lobortis.</p>
        <hr>
        @include('inc.sidebar')
    </div>
</div>
@endsection

hotel-project/resources/views/layouts/room.blade.php
@extends('layouts.theme')
@section('content')
<div class="text-center"><h2>ROOMS</h2></div>
<div class="row">
    <?php $rooms = DB::table('rooms')->get(); ?>
@foreach ($rooms as $room)
    <div class="col-md-4">
        <div class="rooms">
            <a href="/room-detail"><img src="/{{ $room->image }}" alt=""></a>
        </div>
        <div class="rooms-info">
            <center>
                <p>{{ $room->name }}</p>
                <p{{ $room->price }}<sup>$</sup></p>
                @if ($room->status == 1)
                    <p>STATUS: AVAILABLE</p>
                @else
                <p>STATUS: NO AVAILABLE</p>
                @endif
                <span><button><a href="/room-detail">View more</a></button></span>
            </center>
        </div> 
    </div>
@endforeach
    <div class="col-md-4">
        <div class="rooms">
            <a href="/room-detail"><img src="/images/room-2.jpg" alt=""></a>
        </div>
        <div class="rooms-info">
            <center>
                <p>201B ROOMS</p>
                <p>PRICE: 160$</p>
                <p>STATUS: AVAILABLE</p>
                <span><button><a href="/room-detail">View more</a></button></span>
            </center>
        </div> 
    </div>
    <div class="col-md-4">
        <div class="rooms">
            <a href="/room-detail"><img src="/images/room-3.jpg" alt=""></a>
        </div>
        <div class="rooms-info">
            <center>
                <p>201B ROOMS</p>
                <p>PRICE: 160$</p>
                <p>STATUS: AVAILABLE</p>
                <span><button><a href="/room-detail">View more</a></button></span>
            </center>
        </div> 
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <div class="rooms">
            <a href="/room-detail"><img src="/images/room-4.jpg" alt=""></a>
        </div>
        <div class="rooms-info">
            <center>
                <p>201B ROOMS</p>
                <p>PRICE: 160$</p>
                <p>STATUS: AVAILABLE</p>
                <span><button><a href="/room-detail">View more</a></button></span>
            </center>
        </div> 
    </div>
    <div class="col-md-4">
        <div class="rooms">
            <a href="/room-detail"><img src="/images/room-5.jpg" alt=""></a>
        </div>
        <div class="rooms-info">
            <center>
                <p>201B ROOMS</p>
                <p>PRICE: 160$</p>
                <p>STATUS: AVAILABLE</p>
                <span><button><a href="/room-detail">View more</a></button></span>
            </center>
        </div> 
    </div>
    <div class="col-md-4">
        <div class="rooms">
            <a href="/room-detail"><img src="/images/room-6.jpg" alt=""></a>
        </div>
        <div class="rooms-info">
            <center>
                <p>201B ROOMS</p>
                <p>PRICE: 160$</p>
                <p>STATUS: AVAILABLE</p>
                <span><button><a href="/room-detail">View more</a></button></span>
            </center>
        </div> 
    </div>
</div>
@endsection

hotel-project/resources/views/layouts/theme.blade.php
<!DOCTYPE html> 
<html class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Luxury Hotel</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/css/jquery-ui.css">
    <link rel="stylesheet" href="/css/app.css">
</head>
<body>
    <header>
        @include('inc.header')
        @include('inc.banner')
    </header>
    <div class="container">
        @yield('content')
    </div>
    @include('inc.footer')
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/jquery-ui.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/custom.js"></script>
</body>
</html>