hotel-project/app/Http/routes.php
<?php
Route::get('/aboutme', 'PagesController@aboutme');

hotel-project/routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
App::register('Gloudemans\Shoppingcart\ShoppingcartServiceProvider');

Auth::routes();

Route::get('/', 'HomeController@index');

Route::prefix('admin')->group(function () {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.admin-template');
    Route::get('/room/create','RoomController@create');
    Route::get('/room/index','RoomController@index');
    Route::resource('/room','RoomController');
});

Route::get('/contact', function () {
    return view('contact');
});
// Route::post('/contact/submit', 'MessagesController@submit');

Route::resource('category','CategoriesController');
Route::get('/admin', 'AdminController@index')->name('admin.admin-template');
// Route::get('/admin/room/create', 'RoomController@create');


Route::prefix('rooms')->group(function (){
    Route::get('/', 'RoomsController@index');
    Route::get('/room-detail', 'RoomsController@roomDetail');
});
Route::resource('/cart','CartController');
//Route::get('/booking','RoomController@booking');
Route::resource('room','RoomController');
Route::resource('/booking','BookingController');
Route::get('/booking/create/{id}', 'BookingController@create');
Route::get('/customer/create/{id}', 'CustomersController@create');
Route::get('/customer/index', 'CustomersController@index');
Route::resource('/customer','CustomersController');
Route::resource('/search','SearchController');
Route::get('/search','SearchController@create');
Route::get('/room/room/{id}','RoomController@roomCates');

hotel-project/app/Room.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Room extends Model
{
    protected $fillable = ['name','price','description','status','category','image'];
    
    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function checkout()
    {
        return $this->hasMany('App\Checkout');
    }

    public function booking()
    {
        return $this->hasMany('App\Booking');
    }
}

hotel-project/app/Http/Controllers/RoomController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Room;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Input;
use Intervention\Image\ImageManagerStatic as Image;
use Session;
use App\Booking;
use Redirect;
use App\Category;

class RoomController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('room.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('room.booking-form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, array(
            'name' => 'required|max:255',
            'price' => 'required',
            'description' => 'required',
            'category_id' => 'required'
        ));

        // store in the database

        $room = new Room;

        $room->name = $request->name;
        $room->price = $request->price;
        $room->description = $request->description;
        $room->status = $request->status;

        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $filename = $image->getClientOriginalName();
            $location = 'image/' . $filename;
            Image::make($image)->resize(800, 400)->save($location);
        }
        
        $room->image = 'image/'.$filename;
        $room->category_id = $request->category_id;
        $room->save();

        return redirect()->route('admin.admin-template');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function adminShow($id)
    {
        // get the 
        $room = Room::find($id);

        // show the view and pass the  to it
        return \View::make('room.adminShow')
            ->with('room', $room);
    }


    public function show($id)
    {
        // get the 
        $room = Room::find($id);
        $dates = date('Y-m-d');
        // show the view and pass the  to it
        return \View::make('room.show', compact('room','dates'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // get the 
        $room = Room::find($id);

        // show the edit form and pass the
        return \View::make('room.edit')
            ->with('room', $room);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update($id, Request $request)
    {
        // validate
        // read more on validation at http://laravel.com/docs/validation
        
        $this->validate($request, array(
            'name' => 'required|max:255',
            'price' => 'required',
            'description' => 'required',
            'category_id' => 'required'
        ));

            $room = Room::find($id);
            $room->name         = $request->name;
            $room->price        = $request->price;
            $room->description  = $request->description;
            $room->status       = $request->status;
            $room->number_people= $request->number_people;
            $room->available    = $request->available;
            $room->unavailable  = $request->unavailable;
            
            if ($request->hasFile('image')) {
                $image = $request->file('image');
                $filename = $image->getClientOriginalName();
                $location = 'image/' . $filename;
                Image::make($image)->resize(800, 400)->save($location);
            }
        
            $room->image = 'image/'.$filename;
            $room->category_id = $request->category_id;
            $room->save();
        
            Session::flash('message', 'Successfully updated room!');
            return Redirect::to('admin')->with('success', 'Product updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // delete
        $room = Room::find($id);
        $room->delete();

        // redirect
        Session::flash('message', 'Successfully deleted the room!');
        return Redirect::to('admin');
    }
    public function roomCates($id)
    {
        $categories = Category::where('id', '=', $id)->get();
        $rooms = Room::where('category_id','=', $id)->get();

        return view('room.room', compact('rooms', 'categories'));
    }
}

hotel-project/app/Http/Controllers/RoomsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class RoomsController extends Controller
{
    public function index()
    {
        return view('room.index');
    }

    public function roomDetail()
    {
        return view('layouts.room-detail');
    }
}

hotel-project/resources/views/room/booking-form.blade.php
@extends('layouts.theme')
@section('content')

<div>
    {!! Form::open(['route' => 'booking.store', 'method' => 'post']) !!}
    <div class="text-center"><h2>BOOKING FORM</h2></div>
    <div class="well clearfix">
        <fieldset class="well well-form">
            <legend class="well-legend">Booking Details</legend>
            <div class="row">
                <div class="col-xs-4">
                    <label class="control-label" for="booking-date">Check In</label>
                    <div class="form-group input-group">
                        <span class="input-group-addon "><i class="fa fa-calendar"></i></span>
                        <input class="form-control" type="text" name="created_date" id="datefrom" placeholder="Check In" />
                    </div>
                </div>

                <div class="col-xs-4">
                    <label class="control-label" for="booking-date">Check Out</label>
                    <div class="form-group input-group">
                        <span class="input-group-addon "><i class="fa fa-calendar-check-o"></i></span>
                        <input class="form-control" type="text" name="ended_date" id="dateto" placeholder="Check Out" />
                    </div>
                </div>
                <input type="hidden" name="category_id" value="{{ $rooms->category_id }}">
                <input type="hidden" name="amount" value="1">
                <input type="hidden" name="room_id" value="{{ $rooms->id }}">
               <div class="col-xs-2">
                    <label class="control-label" for="form_days">Adults</label>
                    <select class="form-control" id="form_days" name="amount_person">
                        <option selected value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                    </select>
                </div>
                <div class="col-xs-2">
                    <label class="control-label" for="form_days">Children</label>
                    <select class="form-control" id="form_days" name="amount_children">
                        <option selected value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                    </select>
                </div>
            </div>
    <!-- end Row -->
    </fieldset>
    {!! Form::close() !!}
    @if(Session::has('message'))
        <div class="alert alert-info">
            {{ Session::get('message') }}
        </div>
    @endif
    <div class="row">
        <div class="col-xs-12">
            <br/>
           <input type="submit" class="btn btn-warning" value="Continue">
        </div>
    </div>
<!-- end Row -->

    </div>
<!-- end Well -->

</div>
@endsection

hotel-project/resources/views/room/cart-display.blade.php
@extends('layouts.theme')
@section('content')
    
<table class="table table-striped custab">
<thead>
    <tr>
        <th>ID</th>
        <th>Room name</th>
        <th>Quantity</th>
        <th>Price</th>
        <th class="text-center">Action</th>
    </tr>
</thead>
        @foreach ($cartItems as $cartItem)
        <tr>
            <td>{{ $cartItem->id }}</td>
            <td>{{ $cartItem->name }}</td>
            <td>
                {!! Form::open(['route' => ['cart.update',$cartItem->rowId], 'method' => 'PUT']) !!}
                <input class="inpCart" name="qty" type="text" value="{{ $cartItem->qty }}">
                <span><input type="submit" class="btn btn-default" value="OK"></span>
                {!! Form::close() !!}
            </td>
            <td>{{ $cartItem->price }}</td>
            <td class="text-center">
                <a class='btn btn-info btn-xs' href="{{ url('/booking/create', [$cartItem->id])}}">
                    <span class="glyphicon glyphicon-edit"></span> Book</a> 
                <a class="btn btn-danger btn-xs" name="del" href="{{ Cart::remove($cartItem->rowId) }}">
                    <span class="glyphicon glyphicon-remove"></span> Delete</a>
            </td>
        </tr>
         @endforeach
        
</table>
@endsection

hotel-project/resources/views/room/create.blade.php
@section('title', '| Add Room')
<div class="row">
    <!-- Modal -->
    
    <div id="add_project" class="modal fade" role="dialog" style="display: none;">
        <div class="modal-dialog">
        {!! Form::open(['route' => 'room.store',
                            'files' => true,
                            'method' => 'post']) !!}
    
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header login-header">
                    <h4 class="modal-title">Add Room</h4>
                </div>
                <div class="modal-body">
                    <input type="text" placeholder="Room Name" name="name">
                    <input type="text" placeholder="Price" name="price">
                    <textarea name="description" placeholder="Description"></textarea>
                    {{ Form::label('status', 'Status')}}
                    <select placeholder="Status" name="status">
                        <option value="1">1</option>
                        <option value="2">2</option>
                    </select>
                    
                    {{ Form::file('image', array('class' => 'form-control')) }}
                    <?php $categories = DB::table('categories')->pluck('name','id'); ?>
                    {{ Form::label('category_id', 'Category') }}
                    {{ Form::select('category_id', $categories, null, ['class' => 'form-control']) }} 
                </div>
                <div class="modal-footer">
                    <button type="submit" class="cancel">Close</button>
                    <button type="submit" class="add-project">Add</button>
                </div>
            </div>
        </div>
        {!! Form::close() !!}
    </div>
</div>

hotel-project/resources/views/room/cus-info.blade.php
@extends('layouts.theme')
@section('content')
 {!! Form::open(['route' => 'customer.store', 'method' => 'post']) !!} 
 @if(Session::has('message'))
        <div class="alert alert-info">
            {{ Session::get('message') }}
        </div>
    @endif
    <fieldset class="well well-form">
        <legend class="well-legend">Customer</legend>
            <div class="row">
                <div class="col-xs-5">
                    <input type="hidden" name="booking_id" value="{{ $booking->id }}">
                    <label class="control-label" for="firstname">First Name</label>
                    <input class="form-control" type="text" name="firstname" id="firstname" placeholder="First Name" required/>
                    <label class="control-label" for="firstname">Last Name</label>
                    <input class="form-control" type="text" name="lastname" id="firstname" placeholder="Last Name" required/>
                    <label class="control-label" for="phoneNumber">Number</label>
                    <div class="form-group input-group">
                        <span class="input-group-addon primary"><i class="fa fa-phone"></i></span>
                        <input type="text" class="form-control" name="phone" id="phoneNumber" placeholder="Phone Number" pattern="[0].{11,}" required>
                    </div>
                    <label class="control-label" for="email">Email Address</label>
                    <div class="form-group input-group">
                        <span class="input-group-addon primary"><i class="fa fa-envelope-o"></i></span>
                        <input type="email" class="form-control" name="email" id="email" placeholder="Email address" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$" required>
                    </div>
                    <label class="control-label" for="email">Address</label>
                    <div class="form-group input-group">
                        <span class="input-group-addon primary"><i class="fa fa-envelope-o"></i></span>
                        <input type="text" class="form-control" name="address" id="email" placeholder="Address" required>
                    </div>
                </div>
                <div class="col-xs-7">
                    <label class="control-label">Message</label>
                    <textarea class="input-xlarge form-control" id="message" name="message" rows="10" required></textarea>
                </div>
            </div>
            <input type="submit" class="btn btn-warning" value="Send">
    <!-- end Row -->
    </fieldset>
     {!! Form::close() !!} 
@endsection

hotel-project/resources/views/room/edit.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Edit rooms</title>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/app.css">
</head>
<body>
    <div class="container">
        <h2>Edit {{ $room->name }}</h2>
        <div class="col-md-4 image-room">
            <img src="/{{ $room->image }}" alt="">
        </div>
        <div class="col-md-8">

        {{ Form::model($room, array('route' => array('room.update', $room->id),'files' => true, 'method' => 'PUT')) }}

            <div class="form-group">
                {{ Form::label('name', 'Name') }}
                {{ Form::text('name', null, array('class' => 'form-control')) }}
            </div>

            <div class="form-group">
                {{ Form::label('price', 'Price') }}
                {{ Form::text('price', null, array('class' => 'form-control')) }}
            </div>

            <div class="form-group">
                {{ Form::label('description', 'Description') }}
                {{ Form::text('description', null, array('class' => 'form-control')) }}
            </div>

            <div class="form-group">
                {{ Form::label('status', 'Status') }}
                {{ Form::select('status', array('1' => 'Available', '2' => 'Non available'), array('class' => 'form-control')) }}
            </div>
            
            <div class="form-group">
                {{ Form::label('number_people', 'Amount people') }}
                {{ Form::text('number_people', null, array('class' => 'form-control')) }}
            </div>
            <div class="form-group">
                {{ Form::label('available', 'Date Available') }}
                {{ Form::date('available', null, array('class' => 'form-control')) }}
            </div>
            <div class="form-group">
                {{ Form::label('unavailable', 'Date Unavailable') }}
                {{ Form::date('unavailable', null, array('class' => 'form-control')) }}
            </div>
            <div class="form-group">
                {{ Form::label('image', 'Image') }}
                {{ Form::file('image', null, array('class' => 'form-control')) }}
            </div>
            <?php $categories = DB::table('categories')->pluck('name','id'); ?>
            <div class="form-group">
                {{ Form::label('category_id', 'Category') }}
                {{ Form::select('category_id', $categories, array('class' => 'form-control')) }}
            </div>
            {{ Form::submit('Edit the Room!', array('class' => 'btn btn-primary')) }}

        {{ Form::close() }}
        </div>
    </div>
</body>
</html>

hotel-project/resources/views/room/index.blade.php
@extends('layouts.theme')
@section('content')
<div class="text-center"><h2>ROOMS</h2></div>
<div class="row">
    <?php $rooms = DB::table('rooms')->simplePaginate(2); ?>
    @foreach ($rooms as $room)
    <div class="col-md-4">
        <div class="rooms">
            <a href="{{url('/room',[$room->id])}}"><img src="/{{ $room->image }}" alt=""></a>
        </div>
        <div class="rooms-info">
            <center>
                <p>{{ $room->name }}</p>
                <p>{{ $room->price }} $</p>
                @if ($room->status == 1)
                    <p>STATUS: AVAILABLE</p>
                @elseif($room->status == 2)
                    <p>STATUS: NO AVAILABLE</p>
                @else
                    <div><p>Not found</p></div>
                @endif
                <span><button class="btn-button"><a href="{{url('/room',[$room->id])}}">View more</a></button></span>
            </center>
        </div> 
    </div>
    @endforeach
</div>
    <div class="text-center">
        {{ $rooms->links()}}
    </div>
@endsection

hotel-project/resources/views/room/room.blade.php
@extends('layouts.theme')
@section('content')
<div class="form-search">
    @include('layouts.form')
</div>

<div class="col-md-8">
    @foreach ($categories as $category)
    <div class="heading">
        <h2 class="title-anchor title-heading">{{ $category->name }}</h2>
    </div>
    @endforeach
    @foreach ($rooms as $room)
    <div class="content-room">
        <div class="content-container-anchor overlay-container-anchor">
            <p><a href="{{url('/room',[$room->id])}}"><img style="width: 100%" src="/{{ $room->image }}" alt=""></a></p>
            <p><strong>Price</strong><span>:</span><br>
            <span>- {{ $room->price}}/ single room</span><br>

            <p><strong>Hotel rates include:</strong><br>
            Buffet breakfast, VAT and service charge, a free bottle of water/day, free wifi.&nbsp;</p>

            <p><strong>Terms:&nbsp;</strong><br>
            + For children sharing rooms with parents: &nbsp;<br>
            &nbsp; &nbsp; &nbsp;- Under 6 yrs old : Free of charge and breakfast for at most 2 children/room.<br>
            &nbsp; &nbsp; &nbsp;- From 6 to 11 yrs old : 35.000 VND extra charge<br>
            &nbsp; &nbsp; &nbsp;- Over 12 yrs old : 70.000 VND extra charge<br>
            + Room order-form will be kept until 18:00. If the guests want to check in sooner or later, they have to notify the Reception Desk.&nbsp;<br>
            + Check-out time is 12:00. In case of checking out later:&nbsp;<br>
            &nbsp; &nbsp; &nbsp;- From 12:00 to 14:00 : 30% of room’s charge is added&nbsp;<br>
            &nbsp; &nbsp; &nbsp;- From 14:00 to 18:00 : 50% of room’s charge is added<br>
            &nbsp; &nbsp; &nbsp;- After 18:00 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;: 100% of room’s charge is added<br>
            + Check-in time is 14:00. (Guests can check in sooner if rooms are available)</p>

            <p><strong>Terms of payment:</strong><br>
            - Cash or bank transfer&nbsp;<br>
            - Credit cards: Visa, Master, American Expres</p>

            <p>&nbsp;</p>
            <span><a href="{{ route('cart.edit',$room->id) }}"><button class="btn btn-success">Add to wishlist</button></a></span>
            <span><a href="{{url('/room',[$room->id])}}"><button class="btn btn-danger">View more</button></a></span>
        </div>
    </div>
    @endforeach
</div>
<div class="col-md-4">
    @include('inc.sidebar')
</div>

@endsection

hotel-project/resources/views/room/show.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>View rooms</title>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">

</head>
<body>
    @extends('layouts.theme')
    @section('content')
    <div class="col-lg-8">
        <div class="content-room">
            <div class="l-align-center"><h3>Room name: {{ $room->name }}</h3></div>
            <hr>
            <div class="room-content">
                <div class="room-image">
                    <img src="/{{ $room->image }}" alt="">
                    <div class="overlay"><h3>{{ $room->category['name'] }}</h3></div>
                </div>
                <br>
                <table class="table table-border">
                    <tr>
                        <td>Room name</td>
                        <td>{{ $room->name }}</td>
                    </tr>
                    <tr>
                        <td>Price</td>
                        <td>{{ $room->price }}</td>
                    </tr>
                    <tr>
                        <td>Type</td>
                        <td>{{ $room->category['name'] }}</td>
                    </tr>
                    <tr>
                        <td>Date available</td>
                        <td>{{ $room->available }}</td>
                    </tr>
                    <tr>
                        <td>Date unavailable</td>
                        <td>{{ $room->unavailable }}</td>
                    </tr>
                    <tr>
                        <td>Amount people</td>
                        <td>{{ $room->number_people }}</td>
                    </tr>
                    <tr>
                        @if($room->available < $dates)
                            <td>Status</td>
                            <td>
                                <div class="warning-message">
                                    <strong>Out of room</strong>
                                </div>
                            </td>
                        @else
                           <td><a href="{{ route('cart.edit', $room->id) }}"><input type="submit" class="btn btn-success" id="addCart" value="Add to wishlist"></a></td>
                            <td><a href="{{ url('/booking/create', [$room->id])}}"><input type="submit" class="btn btn-danger" value="Book now"></a></td>  
                        @endif
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <!--@include('inc.sidebar')-->
        <div class="room-description">
            <h3>ROOM DESCRIPTION</h3>
            <hr>
            <p>{{ $room->description }}</p>
            <hr>
            @include('inc.sidebar')
        </div>
    </div>
@endsection
</body>
</html>